/* ACTION TYPES */

/* AUTH */
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const AUTHENTICATE_USER_START = 'AUTHENTICATE_USER_START'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const LOGOUT = 'LOGOUT'

/* LABEL */
export const FETCH_ALL_LABELS_START = 'FETCH_ALL_LABELS_START'
export const FETCH_ALL_LABELS_SUCCESS = 'FETCH_ALL_LABELS_SUCCESS'
export const FETCH_ALL_LABELS_ERROR = 'FETCH_ALL_LABELS_ERROR'

export const CREATE_LABEL_START = 'CREATE_LABEL_START'
export const CREATE_LABEL_SUCCESS = 'CREATE_LABEL_SUCCESS'
export const CREATE_LABEL_ERROR = 'CREATE_LABEL_ERROR'
