/* ACTION TYPES */

/* AUTH */
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const AUTHENTICATE_USER_START = 'AUTHENTICATE_USER_START'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const LOGOUT = 'LOGOUT'

/* LABEL */
export const FETCH_ALL_LABELS_START = 'FETCH_ALL_LABELS_START'
export const FETCH_ALL_LABELS_SUCCESS = 'FETCH_ALL_LABELS_SUCCESS'
export const FETCH_ALL_LABELS_ERROR = 'FETCH_ALL_LABELS_ERROR'

export const CREATE_LABEL_START = 'CREATE_LABEL_START'
export const CREATE_LABEL_SUCCESS = 'CREATE_LABEL_SUCCESS'
export const CREATE_LABEL_ERROR = 'CREATE_LABEL_ERROR'

export const DELETE_LABEL_START = 'DELETE_LABEL_START'
export const DELETE_LABEL_SUCCESS = 'DELETE_LABEL_SUCCESS'
export const DELETE_LABEL_ERROR = 'DELETE_LABEL_ERROR'

export const FILTER_POSTS_BY_LABEL_START = 'FILTER_POSTS_BY_LABEL_START'
export const FILTER_POSTS_BY_LABEL_SUCCESS = 'FILTER_POSTS_BY_LABEL_SUCCESS'
export const FILTER_POSTS_BY_LABEL_ERROR = 'FILTER_POSTS_BY_LABEL_ERROR'

export const TOGGLE_CHECK_LABEL_START = 'TOGGLE_CHECK_LABEL_START'
export const TOGGLE_CHECK_LABEL_SUCCESS = 'TOGGLE_CHECK_LABEL_SUCCESS'
export const TOGGLE_CHECK_LABEL_ERROR = 'TOGGLE_CHECK_LABEL_ERROR'

export const DELETE_CHECKED_LABELS_START = 'DELETE_CHECKED_LABELS_START'
export const DELETE_CHECKED_LABELS_SUCCESS = 'DELETE_CHECKED_LABELS_SUCCESS'
export const DELETE_CHECKED_LABELS_ERROR = 'DELETE_CHECKED_LABELS_ERROR'

/* POST */
export const FETCH_ALL_POSTS_START = 'FETCH_ALL_POSTS_START'
export const FETCH_ALL_POSTS_SUCCESS = 'FETCH_ALL_POSTS_SUCCESS'
export const FETCH_ALL_POSTS_ERROR = 'FETCH_ALL_POSTS_ERROR'

export const CREATE_POST_START = 'CREATE_POST_START'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

export const ASSIGN_LABEL_TO_POST_START = 'ASSIGN_LABEL_TO_POST_START'
export const ASSIGN_LABEL_TO_POST_SUCCESS = 'ASSIGN_LABEL_TO_POST_SUCCESS'
export const ASSIGN_LABEL_TO_POST_ERROR = 'ASSIGN_LABEL_TO_POST_ERROR'

export const UPDATE_POSTS_START = 'UPDATE_POSTS_START'
export const UPDATE_POSTS_SUCCESS = 'UPDATE_POSTS_SUCCESS'
export const UPDATE_POSTS_ERROR = 'UPDATE_POSTS_ERROR'

export const REMOVE_LABEL_FROM_POST_START = 'REMOVE_LABEL_FROM_POST_START'
export const REMOVE_LABEL_FROM_POST_SUCCESS = 'REMOVE_LABEL_FROM_POST_SUCCESS'
export const REMOVE_LABEL_FROM_POST_ERROR = 'REMOVE_LABEL_FROM_POST_ERROR'

export const DELETE_POST_START = 'DELETE_POST_START'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR'
